### ISSUE TITLE
Use with cloudhsm

### ISSUE THREAD

**Issue by tomberek** [letsencrypt/pkcs11key#20]
When trying to use CloudHSM with tools backed by pkcs11key (eg: ghostunnel), or even p11tool, I get errors of the form:

```
C_GetAttributeValue failed with error CKR_ATTRIBUTE_TYPE_INVALID : 0x00000012
```
If I comment out the error handling return statements at 
https://github.com/letsencrypt/pkcs11key/blob/master/key.go#L172
https://github.com/letsencrypt/pkcs11key/blob/master/key.go#L183
effectively ignoring those errors, everything seems to work as expected. Is this something you've encountered?

**Comment by jsha** [comment]
I haven't seen this specific symptom, but I have seen CKR_ATTRIBUTE_INVALID before. It's probably one specific attribute that CloudHSM is objecting to when it's used as a template to `findObjects`. That is, one of the fields named `pkcs11.CKA_*`. Rather than commenting out the error handling, try commenting out various of the CKA_ fields until you find a minimal set that works. This will tell you which attribute CloudHSM objects to, and we can check the spec to determine whether the fix should lie in CloudHSM or pkcs11key.

**Comment by jsha** [comment]
I haven't seen any updates on this in a while. I'm going to close for now. If you'd like to provide more info, or a detailed repro case, I will take another look. Thanks!
