### ISSUE TITLE
KeyPool doesn't fully utilize available CPU

### ISSUE THREAD

**Issue by jsha** [letsencrypt/pkcs11key#9]
In a test with pkcs11key_bench_test, I found that performance of KeyPool does not scales poorly with number of sessions. In a test with SoftHSM on a machine with 4 CPUs I got these results:

```
sessions ops/sec
1 760
2 1080
3 1453
4 1543
5 1282
6 1484
```

**Comment by rolandshoemaker** [comment]
I don't think you'll see any increase in performance when using a number of sessions higher than the number of CPUs you have available when using SoftHSM. Using `b.RunParallel` in the benchmark will create a number of goroutines, each time one of those goroutines calls into the SoftHSM module using cgo it will hit a blocking `read` syscall on the OS thread to read the SoftHSM database file. 

Because of this it'll never be able to do more than 4 `Sign` operations in parallel, but this may not be the case for real HSM modules.

**Comment by jsha** [comment]
Agreed that the performance should max out around the number of CPUs, and that's what we see in the data - I went up to 6 just for completeness' sake.

However, I would expect 4 sessions to give us something like 3.5x - 4x performance, not ~2.2x as we see here.

Also note that this may not be the issue we're seeing in prod, with flat performance across any number of sessions.

**Comment by jsha** [comment]
I'm going to chalk this one up to hyperthreading: CPUs that report 4 cores often have 2 hyperthreaded cores, which may not reach full performance, especially for compute-heavy workloads.
